@baseUrl = http://localhost:{{$dotenv PORT}}


### Test al servidor
GET {{baseUrl}}/health

### GET - Obtener todas las tareas
GET {{baseUrl}}/api/tasks

### GET - Obtener task por id
GET {{baseUrl}}/api/tasks/1

### POST - crear task
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
    "title": "Aprender Express",
    "description": "Completar el tutorial de API REST",
    "completed": false
}

### PUT - Actualizar una tarea
PUT {{baseUrl}}/api/tasks/1
Content-Type: application/json

{
    "title": "Tarea 1 actualizada"
}

### PUT - Actualizar una tarea
PUT {{baseUrl}}/api/tasks/1
Content-Type: application/json

{
    "title": "Tarea 1 actualizada -  completada",
    "description": "Tarea completada exitosamente",
    "completed": true,
    "campoextra":"asd"
}
### DELETE - Eliminar una tarea
DELETE {{baseUrl}}/api/tasks/2
